version: '3.8'

services:
  dbdocs-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbdocs-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    env_file:
        - .env.prod