version: '3.8'

services:
  dbdocs-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dbdocs-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    env_file:
        - .env.prod
    environment:
      - VITE_API_DOMAIN=${VITE_API_DOMAIN:-http://10.10.100.90:8081}
      - VITE_BASE_SIGNLINK_URL=${VITE_BASE_SIGNLINK_URL:-http://10.10.100.90:8081}
      - VITE_FIREBASE_CONFIG_OBJECT=${VITE_FIREBASE_CONFIG_OBJECT:-{}}
      - VITE_FIREBASE_VAPID_KEY=${VITE_FIREBASE_VAPID_KEY:-}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
      - VITE_STORAGE_KEY_PREFIX=${VITE_STORAGE_KEY_PREFIX:-}
      - VITE_INTERNAL_SITE_OIDC_CLIENT_ID=${VITE_INTERNAL_SITE_OIDC_CLIENT_ID:-}
      - VITE_INTERNAL_SITE_CLIENT_SECRET=${VITE_INTERNAL_SITE_CLIENT_SECRET:-}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID:-}
      - VITE_FRONTEND_URL=${VITE_FRONTEND_URL:-http://localhost:3000}
      - VITE_GOOGLE_AUTH_URL=${VITE_GOOGLE_AUTH_URL:-/oauth2/authorization/google}
      - VITE_GITHUB_AUTH_URL=${VITE_GITHUB_AUTH_URL:-/oauth2/authorization/github}
